export const ACTIONS = {
    SET_USERS: 'SET_USERS',
    SET_USER: 'SET_USER',
    GET_USER_BY_ID: 'GET_USER_BY_ID',
    UPDATE_USER_BY_ID: 'UPDATE_USER_BY_ID',
    DELETE_USER_BY_ID: 'DELETE_USER_BY_ID'
};